language: cpp
dist: focal

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-9
      - cmake-data
      - cmake
      - libtbb-dev
jobs:
  include:
    # Docs
    - os: linux
      language: python
      python: "3.7"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libtbb-dev
            - doxygen
            - graphviz
      install:
        - pip3 install -r docs/requirements.txt
      script:
        - mkdir ${TRAVIS_BUILD_DIR}/build 
        - cd ${TRAVIS_BUILD_DIR}/build
        - cmake -DCMAKE_BUILD_TYPE=Release -G "CodeBlocks - Unix Makefiles" ..
        - make docs
        - cd ${TRAVIS_BUILD_DIR}
      deploy:
        provider: pages
        local_dir: ./build/docs/sphinx
        skip_cleanup: true
        token: $GITHUB_TOKEN
        keep_history: true
        verbose: true
